### ISSUE TITLE
custom mac address for ath6kl ar6004 hw3.0 firmware

### ISSUE THREAD

**Issue by ggz3** [qca/ath6kl-firmware#1]
I need to change the mac address of wifi SDMAN2 silex module.  
The firmware files are located under      kvalo 

ath6k/AR6004/hw3.0/
      fw-5.bin
      bdata.bin

It is possible to modify the firmware file with new mac address? If yes then which file contains the mac address and what is the offset of the mac address in the file? This will also require crc change. What is the offset of crc in the firmware file and what algorithm is used to calculate the firmware checksum?  

Thanks

**Comment by erikarn** [comment]
hiya,

hm, aren't the MAC addresses in the on-chip OTP or EEPROM or something?


-a

**Comment by ggz3** [comment]
Hi Adrian,


the chipset has its own mac address and that is were wlan0 gets its mac address. But we need to specify our own custom mac address. One way android does it to modify the firmware be

fore the upload. It is changing the mac bytes in FW file and recalculates the crc. After firmware is loaded the new customer mac address is used.

The problem is that I dont now if this particular firmware has this cabability and if yes then how to do it.

Thank you,
G

________________________________
