### ISSUE TITLE
newer firmware?

### ISSUE THREAD

**Issue by ghost** [qca/ath6kl-firmware#2]
I have a device with an AR6004 that requires the 3.0 firmware, which for some reason isn't in the linux-firmware upstream repository. But when I go to use this repository's firmware, the driver appears to work with it but it claims that the firmware lacks the RSN-CAP-OVERRIDE capability and so it has disabled 802.11n or HT feature. The exact error text is as follows: Firmware lacks RSN-CAP-OVERRIDE, so HT (802.11n) is disabled.

Is there any possibility of a newer firmware being available that would address the issue that the kernel driver is reporting? Thanks.

**Comment by aericktoes** [comment]
I can confirm this exact behaviour on my device as well. Bluetooth doesn't work either, but I'm not sure if that is due to the firmware.

**Comment by IGNNE** [comment]
Same here. Actually, if you look around, there are some newer firmwares from Android phones scattered on the internet. But while those work on my ar6004, they produce a lot of errors in the dmesg and seem to advertise less features.

By the way, did anyone manage to make P2P with the ath6k work?

**Comment by personalizedrefrigerator** [comment]
https://git.rigado.com/vesta/vesta-firmware/-/tree/master/firmware/ath6k might have newer firmware... I have yet to test it (and found this by searching on the internet, so don't necessarily trust the source).

**Comment by aerickt** [comment]
@personalizedrefrigerator just tried out the new firmware and it works better for me as well. No longer cutting out after 30 minutes and improved performance on some Wi-Fi networks.

**Comment by IGNNE** [comment]
For me, this driver crashes almost constantly. This spams lots of stack traces to dmesg / journal, causing noticeable cpu load. If I ping my tablet, it shows lots of packet loss and the ping time jumps from 2 ms to >100 ms. SSH connections seem laggy as well. With the "old" firmware, I might have occasional hickups, but in between those, wifi worked okay. 

Btw, I've been using [this script](https://www.studioteabag.com/science/dell-venue-pro-linux/#iwup.py) to work around the issue with disconnects.

**Comment by IGNNE** [comment]
The same repo seems to have firmware files for bluetooth (`firmware/ar3k/1020201/PS_ASIC.pst`), anyone tried these?

**Comment by aerickt** [comment]
@IGNNE I placed the folder in `/usr/lib/firmware` but to no avail. `rfkill list` doesn't show bluetooth.
